version: '3.7'
services:
  js-polyfill:
    container_name: js-polyfill
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t1", "--spider", "http://localhost:8801/v3/polyfill.min.js"]
      interval: 30s
      timeout: 30s
      retries: 3
    image: js-polyfill
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - '8801:8801'
